# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  #########################################################################################
  # Note: This file has been generated by Terragrunt using the terragrunt init command.   #
  # Any modifications made to this file may be overwritten the next time terragrunt init  #
  # is executed.                                                                          #
  #########################################################################################
  data "aws_caller_identity" "caller" {}
  data "aws_partition" "current" {}
  data "aws_region" "current" {}
