# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  #########################################################################################
  # Note: This file has been generated by Terragrunt using the terragrunt init command.   #
  # Any modifications made to this file may be overwritten the next time terragrunt init  #
  # is executed.                                                                          #
  #########################################################################################
  provider "aws" {
    region  = "us-west-2"
    profile = "dev"

    default_tags {
      tags = {
        Owner = "infrastructure"
        Platform = "infrastructure"
        Environment = "dev"
        CostCenter  = "infrastructure"
        TerraformRepo = "infrastructure"
        TerraformPath = "dev/codecommit"
      }
    }
  }

  provider "aws" {
    region  = "us-west-2"
    profile = "prod"
    alias   = "prd"

    default_tags {
      tags = {
        Environment = "prd"
        Owner       = "YOUREMAIL@gmail.com"
        Platform    = "infrastructure"
        CostCenter  = "infrastructure"
        TerraformRepo = "infrastructure"
        TerraformPath = "dev/codecommit"
      }
    }
  }

  provider "aws" {
    region  = "us-west-2"
    profile = "test"
    alias   = "stg"

    default_tags {
      tags = {
        Environment = "stg"
        Owner       = "YOUREMAIL@gmail.com"
        Platform    = "infrastructure"
        CostCenter  = "infrastructure"
        TerraformRepo = "infrastructure"
        TerraformPath = "dev/codecommit"
      }
    }
  }

  provider "aws" {
    region  = "us-west-2"
    profile = "dev"
    alias   = "dev"

    default_tags {
      tags = {
        Environment = "dev"
        Owner       = "YOUREMAIL@gmail.com"
        Platform    = "infrastructure"
        CostCenter  = "infrastructure"
        TerraformRepo = "infrastructure"
        TerraformPath = "dev/codecommit"
      }
    }
  }

  ## Required for non hashicorp providers
  terraform {
    required_providers {
      docker = {
        source  = "kreuzwerker/docker"
        version = "3.0.2"
      }
    }
  }

