# ----------------------------------------------------
# ENVIRONMENT TERRAGRUNT CONFIGURATION
# ----------------------------------------------------

locals {
    # Read hcl from region
    region_hcl_path = find_in_parent_folders("region.hcl")
    region_hcl_config = read_terragrunt_config(local.region_hcl_path)

    aws_provider_region = try(local.region_hcl_config.locals.aws_provider_region, "us-west-2")
    aws_profile         = "dev"
    account_id          = "your-acct-#"
    environment_name    = "${reverse(split("/", get_path_from_repo_root()))[0]}"
}

generate "environment_vars" {
    path = "tg_environment_vars.tf"
    if_exists = "overwrite_terragrunt"
    contents  = <<EOF
    #########################################################################################
    # Note: This file has been generated by Terragrunt using the terragrunt init command.   #
    # Any modifications made to this file may be overwritten the next time terragrunt init  #
    # is executed.                                                                          #
    #########################################################################################
    locals {
        stack_name = basename(abspath(path.module))
    }
    EOF
}
