# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-backend-dev-jjm"
    dynamodb_table = "terraform-backend-lock-table-dev"
    encrypt        = true
    key            = "applications/ops/us-west-2/environments/dev/catpipeline/terraform.tfstate"
    profile        = "dev"
    region         = "us-west-2"
  }
}
