# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  #########################################################################################
  # Note: This file has been generated by Terragrunt using the terragrunt init command.   #
  # Any modifications made to this file may be overwritten the next time terragrunt init  #
  # is executed.                                                                          #
  #########################################################################################
  data "aws_caller_identity" "caller" {}
  data "aws_partition" "current" {}
  data "aws_region" "current" {}

  data "aws_vpc" "default_vpc" {
    default  = true

  }

  data "aws_subnets" "public" {
    filter {
      name   = "vpc-id"
      values = [data.aws_vpc.default_vpc.id]
    }

    filter {
      name   = "tag:Name"
      values = ["playground-vpc-public-*"]
    }
  }

  data "aws_subnets" "private" {
    filter {
      name   = "vpc-id"
      values = [data.aws_vpc.default_vpc.id]
    }

    filter {
      name   = "tag:Name"
      values = ["playground-vpc-private-*"]
    }
  }

  data "aws_subnet" "private_subnet_list" {
    count = length(data.aws_subnets.public.ids)
    id    = data.aws_subnets.private.ids[count.index]
  }

  data "aws_subnet" "public_subnet_list" {
    count = length(data.aws_subnets.private.ids)
    id    = data.aws_subnets.private.ids[count.index]
  }
