# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    #########################################################################################
    # Note: This file has been generated by Terragrunt using the terragrunt init command.   #
    # Any modifications made to this file may be overwritten the next time terragrunt init  #
    # is executed.                                                                          #
    #########################################################################################
    locals {
        stack_name = basename(abspath(path.module))
    }
