# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  #########################################################################################
  # Note: This file has been generated by Terragrunt using the terragrunt init command.   #
  # Any modifications made to this file may be overwritten the next time terragrunt init  #
  # is executed.                                                                          #
  #########################################################################################
  provider "aws" {
    region  = "us-west-2"
    profile = "dev"

    default_tags {
      tags = {
        Owner = "YOUREMAIL@gmail.com"
        Platform = "ops"
        Environment = "dev"
        CostCenter  = "ops"
        TerraformRepo = "applications"
        TerraformPath = "ops/us-west-2/environments/dev/catpipeline"
      }
    }
  }

  provider "aws" {
    region  = "us-west-2"
    profile = "iterativescopes"
    alias   = "prd"

    default_tags {
      tags = {
        Environment = "prd"
        Owner       = "YOUREMAIL@gmail.com"
        Platform    = "ops"
        CostCenter  = "ops"
        TerraformRepo = "infrastructure"
        TerraformPath = "ops/us-west-2/environments/dev/catpipeline"
      }
    }
  }

  provider "aws" {
    region  = "us-west-2"
    profile = "iterativescopes"
    alias   = "stg"

    default_tags {
      tags = {
        Environment = "stg"
        Owner       = "YOUREMAIL@gmail.com"
        Platform    = "ops"
        CostCenter  = "ops"
        TerraformRepo = "infrastructure"
        TerraformPath = "ops/us-west-2/environments/dev/catpipeline"
      }
    }
  }

  provider "aws" {
    region  = "us-west-2"
    profile = "platform-dev"
    alias   = "dev"

    default_tags {
      tags = {
        Environment = "dev"
        Owner       = "YOUREMAIL@gmail.com"
        Platform    = "ops"
        CostCenter  = "ops"
        TerraformRepo = "infrastructure"
        TerraformPath = "ops/us-west-2/environments/dev/catpipeline"
      }
    }
  }

  ## Required for non hashicorp providers
  terraform {
    required_providers {
      docker = {
        source  = "kreuzwerker/docker"
        version = "3.0.2"
      }
      kubernetes = {
        source  = "hashicorp/kubernetes"
        version = ">= 2.23"
      }
      helm = {
        source  = "hashicorp/helm"
        version = ">= 2.11.0"
      }
      kubectl = {
        source  = "gavinbunney/kubectl"
        version = ">= 1.7.0"
      }
      aws = {
        source  = "hashicorp/aws"
        version = "~> 5.0"
      }
    }
  }

